name: Deploy with Firebase

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build the page
        run: npm run build
      - name: Deploy with Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          # see via cmd: firebase login:ci
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
